FROM  jenkins/jenkins:lts

USER root

RUN apt-get -qq update \
    && apt-get -qq -y install \
    curl

RUN curl -sSL https://get.docker.com/ | sh

RUN usermod -a -G staff,docker jenkins
RUN gpasswd -a jenkins staff

USER jenkins
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Auto Setup Scripts
COPY Groovy/* /usr/share/jenkins/ref/init.groovy.d/
COPY Jobs/*.file /var/jenkins_home/config/initials/
